name: Latest hashnode blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest hashnode blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in https://thecodingprocess.hashnode.dev posts
        uses: favour-olumese/blog-post-workflow@v1
        with:
          feed_list: "https://thecodingprocess.hashnode.dev/rss.xml"
